### PR TITLE
Include server networks in generated inventory and update README.md

### PR DESCRIPTION
**Pull request by brtkwr**

### CODE REVIEW

**Comment by brtkwr** [comment]
Ready for review ✅

**Review by markgoddard — APPROVED** [review]
Looks sensible

**Comment by brtkwr** [comment]
Still don't have the power to update this on Ansible galaxy.... mind doing that for me please @markgoddard

**Comment by markgoddard** [comment]
Travis should update this using the notification webhook. It was updated 9 minutes ago: https://galaxy.ansible.com/stackhpc/os-container-infra/

**Pull request merged**
