### PR TITLE
Remove `openstack` from `os_container_infra_environment_group` which …

### PR DESCRIPTION
**Pull request by brtkwr**
…causes problems

### CODE REVIEW

**Review by oneswig — APPROVED** [review]
Subtle but effective

**Comment by markgoddard** [comment]
What's the problem that this fixes? We use this with cluster-infra to put all hosts in a group representing their environment, e.g. staging vs. production.

**Comment by brtkwr** [comment]
This is supposed to fix manila share variables being rendered correctly but it isn't doing at the moment when you are not using clouds.yaml

**Comment by brtkwr** [comment]
Unfortunately this doesn't fix it... commenting out

**Pull request closed without merging**
